### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ZhaoChenxi123** [gcallah/Emu86#28]
Hello
 I have got some errors while trying to install the newest version. Here is the error message:
 ERROR: Command errored out with exit status 1:
     command: /root/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rfb9cmbx/emu86/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rfb9cmbx/emu86/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-rfb9cmbx/emu86/pip-egg-info
         cwd: /tmp/pip-install-rfb9cmbx/emu86/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rfb9cmbx/emu86/setup.py", line 3, in <module>
        with open('Emu86 Kernel PYPI Description.md', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'Emu86 Kernel PYPI Description.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I wonder that there is a file called 'Emu86 Kernel PYPI Description.md' missing, and when I try to  install the 0.0.9.3 version of emu86, the error message is gone

**Comment by tbhaxor** [comment]
I am too facing this issue.

**Comment by cindylee0113** [comment]
Hello, can you all try installing the latest version, v0.0.9.6? Not exactly sure why it reports that the file is missing when it's there, but please let us know if the latest version also doesn't work!

**Comment by ZhaoChenxi123** [comment]
@cindylee0113 It seems that the same error still occurs
Defaulting to user installation because normal site-packages is not writeable
Collecting emu86==0.0.9.6
  Downloading emu86-0.0.9.6.tar.gz (46 kB)
     |████████████████████████████████| 46 kB 43 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q6_7ddbb/emu86/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q6_7ddbb/emu86/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-q6_7ddbb/emu86/pip-egg-info
         cwd: /tmp/pip-install-q6_7ddbb/emu86/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q6_7ddbb/emu86/setup.py", line 3, in <module>
        with open('Emu86 Kernel PYPI Description.md', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'Emu86 Kernel PYPI Description.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by cindylee0113** [comment]
Can you try again with the latest version -- v.0.0.10? We added a MANIFEST.in file to handle the missing file error.

**Comment by ZhaoChenxi123** [comment]
@cindylee0113  Thanks for your help, and the installation error is solved, but there is another problem for me: after I type in the code shown in the tutorial and then run the code(push shift+enter), nothing will happen. 

Here is my code:
```
mov edx, 2
mov ebx, 16
```

after I ran these code in one cell, nothing happened, but the tutorial shows that there will be a list, I wonder there is something wrong

**Comment by cindylee0113** [comment]
@ZhaoChenxi123 Can you show a screenshot of the cell and the settings? Did you select markdown for the cell instead of code?

**Comment by ZhaoChenxi123** [comment]
@cindylee0113  the screenshot:
![msedge_hjooyaBwwt](https://user-images.githubusercontent.com/42257910/79683591-d11b0600-825d-11ea-8ae2-f62e0bd28d4f.png)
and the config file of my jupyter lab:
```
c.NotebookApp.allow_origin = '*'
c.NotebookApp.ip = '0.0.0.0'
c.NotebookApp.open_browser = False
```

**Comment by cindylee0113** [comment]
@ZhaoChenxi123 Can you update to the newest version 0.1.0 and try again? We accidentally left out a metadata field when rendering the results.

**Comment by ZhaoChenxi123** [comment]
@cindylee0113 It can work now! Thank you for your effort and creation of such a useful tool to learn assembly language!

**Comment by cindylee0113** [comment]
No problem! If you find any other bugs or have any features you would like us to implement, please feel free to let us know. Thanks!
